---
title: "Protective Effect Paper"
author: "Abigail Wukitch"
date: "7/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load libraries and data}
library(survival)
library(RColorBrewer)
library(ggplot2)
library(rlang)

rm(list=ls()) #removes all old variables
E.fae_P.rett = read.csv("E.fae-P.rett.csv")
S.m_P.rett_no_extremes = read.csv("S.m-P.rett no extremes.csv")
S.m_P.rett_extremes = read.csv("S.m-P.rett extremes.csv")
S.m_P.snee = read.csv("S.m-P.snee.csv")
P.rett_varied_primary = read.csv("Varied primary S.m-P.rett.csv")
P.snee_varied_primary = read.csv("Varied primary S.m-P.snee.csv")
```

```{r, E.fae-P.rett survival data}
E.fae_P.rett$primary <- relevel(E.fae_P.rett$primary, "PBS")

#KAPLAN MEIER
table(E.fae_P.rett$primary, E.fae_P.rett$secondary_dose) #tells you the number of flies in each condition
png(file="E.fae-P.rett.png", width=1200, heigh=900, res=130) #determines where the graph will be saved
par(mar=c(4,5,1,1)) #sets the margins around the graph so there is room for the labels
#The graph
plot(survfit(Surv(E.fae_P.rett$day, E.fae_P.rett$status) ~ E.fae_P.rett$primary + E.fae_P.rett$secondary_dose), 
     col=c("#B5E8FC", "#09B6FC", "#055df5", "#0600a8"), #line color
     lty=c(3, 3, 3, 3, 1, 1, 1, 1), #line type
     lwd=5, #line width
     yaxt='n', #hide the y axis so I can customize it
     xaxt='n', #hide the x axis so I can customize itS
     ylab="proportion alive", #label for the y-axis
     xlab="days post-secondary infection", #label for the x-axis
     cex.lab=2.5, #font size of axis labels
     xlim=c(0,7), #determines range of the x-axis
     xaxs='i') #makes the data flush with the axis 
#Y axis
axis(2, #left side
     las=2, #perpendicular to the axis
     cex.axis=1.5, #font size
     lwd=5) #line width
#X axis
axis(1, #bottom of the graph
     cex.axis=1.5, #font size
     lwd=5) #line width
box(lwd=5)
#The legend
legend("topright", #location
       bty="n", #no box around the legend
       c("PBS-P.rett 0.001", "PBS-P.rett 0.01", "PBS-P.rett 0.1", 'PBS-P.rett 1.0', "E.fae-P.rett 0.001", "E.fae-P.rett 0.01", "E.fae-P.rett 0.1", "E.fae-P.rett 1.0"), #labels in the legend
       col=c("#B5E8FC", "#09B6FC", "#055df5", "#0600a8"), #colors for the legend lines, cycles through
       lty=c(3, 3, 3, 3, 1, 1, 1, 1), #line type for legend lines
       lwd=5, #line width for legend lines
       cex=1) #font size

#STATISTICS
#Generate a Cox proportional Hazards model which assesses the contribution of infectious dose while controlling for replicate
E.fae_P.rett$secondary_dose <- as.factor(E.fae_P.rett$secondary_dose)
E.fae_P.rett_coxph <- coxph(Surv(day, status) ~ secondary_dose + primary + rep + primary:secondary_dose + rep:secondary_dose + rep:primary, data = E.fae_P.rett)
summary(E.fae_P.rett_coxph)
anova(E.fae_P.rett_coxph)
```

```{r, S.m-P.rett no extremes survival data}
S.m_P.rett_no_extremes$primary <- relevel(S.m_P.rett_no_extremes$primary, "PBS")
table(S.m_P.rett_no_extremes$primary, S.m_P.rett_no_extremes$secondary_dose)

#THE GRAPH
png(file="S.m_P.rett_no_extremes.png",width=1200,height=900,res=130)
par(mar=c(4,5,1,1)) #sets the margins around the graph so there is room for the labels
plot(survfit(Surv(S.m_P.rett_no_extremes$day, S.m_P.rett_no_extremes$status) ~ S.m_P.rett_no_extremes$primary + S.m_P.rett_no_extremes$secondary_dose), col=c("#B5E8FC",  "#09B6FC", "#055df5", "#003694"), lty=c(3, 3, 3, 3, 1, 1, 1, 1), lwd=5,yaxt='n', xaxt='n', ylab="proportion alive", xlab="days post-secondary infection", cex.lab=2.5, xlim=c(0,7), xaxs='i') 
axis(2, las=2, cex.axis=1.5, lwd=5)
axis(1, cex.axis=1.5, lwd=5)
box(lwd=5)

#THE LEGEND
legend("topright",inset=0, bty="n" , c("PBS-P.rett 0.01", "PBS-P.rett 0.1", "PBS-P.rett 1.0", "PBS-P.rett 2.0", "S.m-P.rett 0.01", "S.m-P.rett 0.1", "S.m-P.rett 1.0", "S.m-P.rett 2.0"),col=c("#B5E8FC", "#09B6FC", "#055df5", "#003694"),lty=c(3, 3, 3, 3, 1, 1, 1, 1),lwd=5, cex=1)

#STATISTICS
S.m_P.rett_no_extremes$secondary_dose <- as.factor(S.m_P.rett_no_extremes$secondary_dose)
S.m_P.rett_no_extremes_coxph <- coxph(Surv(day, status) ~ secondary_dose + primary + rep + primary:secondary_dose + rep:secondary_dose + rep:primary, data = S.m_P.rett_no_extremes)
summary(S.m_P.rett_no_extremes_coxph)
anova(S.m_P.rett_no_extremes_coxph)
```

```{r, S.m-P.rett extremes survival data}
S.m_P.rett_extremes$primary <- relevel(S.m_P.rett_extremes$primary, "PBS")
table(S.m_P.rett_extremes$primary, S.m_P.rett_extremes$secondary_dose)

#THE GRAPH
png(file="S.m_P.rett_extremes.png",width=1200,height=900,res=130)
par(mar=c(4,5,1,1)) #sets the margins around the graph so there is room for the labels
plot(survfit(Surv(S.m_P.rett_extremes$day, S.m_P.rett_extremes$status) ~ S.m_P.rett_extremes$primary + S.m_P.rett_extremes$secondary_dose), col=c("gray", "#B5E8FC",  "#09B6FC", "#055df5", "#003694", "black"), lty=c(3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1), lwd=5, yaxt='n', xaxt='n', ylab="proportion alive", xlab="days post-secondary infection", cex.lab=2.5, xlim=c(0,7), xaxs='i') 
axis(2, las=2, cex.axis=1.5, lwd=5)
axis(1, cex.axis=1.5, lwd=5)
box(lwd=5)

#THE LEGEND
legend("topright",inset=0, bty="n" , c("PBS-PBS", "PBS-P.rett 0.1", "PBS-P.rett 1.0", "PBS-P.rett 2.0", "PBS-P.rett 3.0", "PBS-P.rett 5.0", "S.m-PBS", "S.m-P.rett 0.1", "S.m-P.rett 1.0", "S.m-P.rett 2.0", "S.m-P.rett 3.0", "S.m-P.rett 5.0"),col=c("gray", "#B5E8FC",  "#09B6FC", "#055df5", "#003694", "black"),lty=c(3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1),lwd=5, cex=1)

#STATISTICS
S.m_P.rett_extremes$secondary_dose <- as.factor(S.m_P.rett_extremes$secondary_dose)
S.m_P.rett_extremes_coxph <- coxph(Surv(day, status) ~ secondary_dose + primary + rep + primary:secondary_dose + rep:secondary_dose + rep:primary, data = S.m_P.rett_extremes)
summary(S.m_P.rett_extremes_coxph)
anova(S.m_P.rett_extremes_coxph)
```

```{r, S.m-P.snee survival data}
table(S.m_P.snee$primary, S.m_P.snee$secondary_dose)

png(file="S.m_P.snee.png",  width = 1700, height = 1500, res = 300)
#par(mar=c(4,4,0.1,0.1)) #sets the margins around the graph so there is room for the labels
plot(survfit(Surv(S.m_P.snee$hour, S.m_P.snee$status) ~ S.m_P.snee$primary + S.m_P.snee$secondary_dose), col=c("gray", "#B5E8FC", "#75D6FD", "#09B6FC", "#055df5"), lty=c(3, 3, 3, 3, 3, 1, 1, 1, 1, 1), lwd=2.3, yaxt='n', xaxt='n', ylab="Proportion Alive", xlab="Hours Post-Secondary Infection", cex.lab=1.3, xlim=c(10,48), xaxs='i', ylim=c(0, 1.05), yaxs='i') 
axis(2, las=2, cex.axis=1, lwd=4.5) 
axis(1, cex.axis=1, lwd=4.5)
box(lwd=4.5)

legend("bottomleft", bty="n" , c("PBS-PBS", "0.001", "PBS-0.01", "PBS-0.1", "PBS-1.0", "S.m-PBS", "S.m-0.001", "S.m-0.01", "S.m-0.1", "S.m-1.0"),col=c("gray", "#B5E8FC", "#75D6FD", "#09B6FC", "#055df5"), lty=c(3, 3, 3, 3, 3, 1, 1, 1, 1, 1),lwd=4, cex=1)

#STATISTICS
S.m_P.snee$secondary_dose <- as.factor(S.m_P.snee$secondary_dose)
S.m_P.snee_coxph <- coxph(Surv(day, status) ~ secondary_dose + primary + rep + primary:secondary_dose + rep:secondary_dose + rep:primary, data = S.m_P.snee)
summary(S.m_P.snee_coxph)
anova(S.m_P.snee_coxph)
```

```{r, S.m-P.rett varied primary survival data}
P.rett_varied_primary = subset(P.rett_varied_primary, secondary == "P.rett")
table(P.rett_varied_primary$condition)

png(file="P.rett_varied_primary.png",  width = 1700, height = 1500, res = 300)
#par(mar=c(4,4,0.1,0.1)) #sets the margins around the graph so there is room for the labels
plot(survfit(Surv(P.rett_varied_primary$day, P.rett_varied_primary$status) ~ P.rett_varied_primary$condition), col=c("gray", "#B5E8FC", "#75D6FD", "#09B6FC", "#055df5", "#003694"), lty=c(1, 1, 1, 1, 1, 1), lwd=3.4, yaxt='n', xaxt='n', ylab="Proportion Alive", xlab="Days Post-Secondary Infection", cex.lab=1.3, xlim=c(0,7), xaxs='i', ylim=c(0, 1.05), yaxs='i')  
axis(2, las=2, cex.axis=1, lwd=4.5) 
axis(1, cex.axis=1, lwd=4.5)
box(lwd=4.5)

legend("bottomleft", bty="n" , c("PBS-P.rett 2.0", "S.m 0.001-P.rett 2.0", "S.m 0.01-P.rett 2.0", "S.m 0.1-P.rett 2.0", "S.m 1.0-P.rett 2.0", "S.m 2.0-P.rett 2.0"),col=c("gray", "#B5E8FC", "#75D6FD", "#09B6FC", "#055df5", "#003694"),lty=c(1, 1, 1, 1, 1, 1),lwd=5, cex=1)
```

```{r, S.m-P.snee varied primary survival data}
P.snee_varied_primary = subset(P.snee_varied_primary, secondary == "P.snee")
table(P.snee_varied_primary$condition)

png(file="P.snee_varied_primary.png",  width = 1700, height = 1500, res = 300)
#par(mar=c(4,4,0.1,0.1)) #sets the margins around the graph so there is room for the labels
plot(survfit(Surv(P.snee_varied_primary$hour, P.snee_varied_primary$status) ~ P.snee_varied_primary$condition), col=c("gray", "#B5E8FC", "#75D6FD", "#09B6FC", "#055df5", "#003694"), lty=c(1, 1, 1, 1, 1, 1), lwd=3.4, yaxt='n', xaxt='n', ylab="Proportion Alive", xlab="Hours Post-Secondary Infection", cex.lab=1.3, xlim=c(10,48), xaxs='i', ylim=c(0, 1.05), yaxs='i')  
axis(2, las=2, cex.axis=1, lwd=4.5) 
axis(1, cex.axis=1, lwd=4.5)
box(lwd=4.5)

legend("bottomleft", bty="n" , c("PBS-P.snee 2.0", "S.m 0.001-P.snee 2.0", "S.m 0.01-P.snee 2.0", "S.m 0.1-P.snee 2.0", "S.m 1.0-P.snee 2.0", "S.m 2.0-P.snee 2.0"),col=c("gray", "#B5E8FC", "#75D6FD", "#09B6FC", "#055df5", "#003694"),lty=c(1, 1, 1, 1, 1, 1),lwd=5, cex=1)
```