---
title: "Bacterial_load"
author: "Abigail Wukitch"
date: "5/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is R code for the bacterial load experiments

```{r load data and define variables}
library(RColorBrewer)
library(ggplot2)
library(agricolae)

rm(list=ls()) #removes all old variables
E.fae_data_with2 = read.csv("E.fae resistance data.csv")
E.fae_data = subset(E.fae_data_with2, dose != 2)
S.m_data = read.csv("S.m resistance data.csv")

```

**10 Hour Bacterial Load Box and Whisker Plot**

E.fae
```{r Bacterial load box and whisker}
table(E.fae_data$dose)

png(file="E.fae_bacterial_load.png",width=1200,height=900,res=130)
ggplot(E.fae_data, aes(x = as.character(dose), y = log(load), fill = primary)) +
  scale_fill_manual(values=c("#09B6FC", "gray")) +
  geom_boxplot() + 
  theme_classic(base_size = 25) + 
  xlab("secondary dose of P. rettgeri") +
  ylab("log(calculated bacterial load)") +
  geom_point(aes(fill=primary), size = 1.6, position=position_jitterdodge())

```

S.m 

```{r Bacterial load box and whisker}
table(S.m_data$primary, S.m_data$secondary)

png(file="S.m_bacterial_load.png",width=1200,height=900,res=130)
ggplot(S.m_data, aes(x = secondary, y = log(CFU_equiv), fill = factor(primary, levels = c("s.m 0.1", "control")))) +
  scale_fill_manual(values=c("#09B6FC","gray")) +
  geom_boxplot() + 
  theme_classic(base_size = 25) + 
  xlab("secondary dose of P. rettgeri") +
  ylab("log(calculated bacterial load)") + 
  scale_x_discrete(labels = c("0.001", "0.01", "0.1", "1.0", "2.0")) +
  geom_point(aes(fill=primary), size = 1.6, position=position_jitterdodge()) + 
  guides(fill=guide_legend(title="primary"))



```
